RadCms.Web/Areas/Carousel/Controllers/ItemCmsController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace RadCms.Web.Areas.Carousel.Controllers
{
    using RadCms.Data;
    using RadCms.Entities;
    using Mvc;

    public class ItemCmsController : CmsControllerBase
    {
        private IRepository<Carousel> _carouselRepo;

        public ItemCmsController(IRepository<Carousel> carouselRepo)
        {
            _carouselRepo = carouselRepo;
        }

        //
        // GET: /Carousel/

        public ViewResult Index()
        {
            return View(_carouselRepo.GetAll().ToList());
        }

        //
        // GET: /Carousel/Details/5

        public ViewResult Details(int id)
        {
            Carousel carousel = _carouselRepo.Get(id);
            return View(carousel);
        }

        [HttpPost]
        public ActionResult Do(string id, string act)
        {
            int sid = Convert.ToInt32(id);
            Carousel slide = _carouselRepo.Get(sid);

            switch (act)
            {
                case "delete":
                    _carouselRepo.Delete(slide);
                    _carouselRepo.Save();

                    break;

                case "edit":

                    //db.Entry(slide).State = EntityState.Modified;
                    //db.SaveChanges();

                    return RedirectToAction("Edit", new { id = id });

                case "cancel":

                    break;
            }

            return RedirectToAction("Index");
        }

        //
        // GET: /Carousel/Create

        public ActionResult Create()
        {
            return View(new Carousel());
        } 

        //
        // POST: /Carousel/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Carousel carousel)
        {
            if (ModelState.IsValid)
            {
                _carouselRepo.Add(carousel);
                _carouselRepo.Save();
                return RedirectToAction("Index");  
            }

            return View(carousel);
        }
        
        //
        // GET: /Carousel/Edit/5
 
        public ActionResult Edit(int id)
        {
            Carousel carousel = _carouselRepo.Get(id);
            return View(carousel);
        }

        //
        // POST: /Carousel/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Carousel carousel)
        {
            if (ModelState.IsValid)
            {
                _carouselRepo.Update(carousel);
                _carouselRepo.Save();
                return RedirectToAction("Index");
            }
            return View(carousel);
        }

        //
        // GET: /Carousel/Delete/5
 
        public ActionResult Delete(int id)
        {
            Carousel carousel = _carouselRepo.Get(id);
            return View(carousel);
        }

        //
        // POST: /Carousel/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Carousel carousel = _carouselRepo.Get(id);
            _carouselRepo.Delete(carousel);
            _carouselRepo.Save();
            return RedirectToAction("Index");
        }
    }
}

RadCms.Web/Areas/ContentType/Controllers/ItemCmsController.cs
using RadCms.Data;
using RadCms.Mvc;
using RadCms.Security;
using System;
using System.Linq;
using System.Web.Mvc;

namespace RadCms.Web.Areas.ContentType.Controllers
{
    using Entities;

    public class ItemCmsController : CmsControllerBase
    {
        private IRepository<ContentType> _repo;
        private IRepository<NaviNode> _nodeRepo;
        private IRepository<CmsPage> _pageRepo;
        private IRepository<PageLayout> _layoutRepo;
        public ItemCmsController(IRepository<ContentType> repo, IRepository<NaviNode> nodeRepo, IRepository<CmsPage> pageRepo, IRepository<PageLayout> layoutRepo)
        {
            if (!SecurityHelper.IsAdmin())
            {
                throw new UnauthorizedAccessException();
            }
            _repo = repo;
            _nodeRepo = nodeRepo;
            _pageRepo = pageRepo;
            _layoutRepo = layoutRepo;
        }

        public ActionResult Index()
        {
            var items = _repo.GetAll();
            return View(items);
        }

        public JsonResult Nodes(int id)
        {
            var items = _nodeRepo.GetAll().Where(e => e.Type.Id == id).Select(e=> new
            {
                Id = e.Id,
                Title = e.NodeName,
                Type = e.Type.Title
            });
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Layouts(int id)
        {
            var items = _layoutRepo.GetAll().Where(e => e.Type.Id == id).Select(e=> new
            {
                Id = e.Id,
                Title = e.Title,
                Type = e.Type.Title
            });
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Pages(int id)
        {
            var items = _pageRepo.GetAll().Where(e => e.Type.Id == id).Select(e=> new {
                Id = e.Id,
                Title = e.Title,
                Url = e.Url,
                Type = e.Type.Title
            });
            return Json(items, JsonRequestBehavior.AllowGet);
        }
    }
}

RadCms.Web/Areas/Carousel/Views/ItemCms/Create.cshtml
@model RadCms.Entities.Carousel
@{
    ViewBag.Title = "Create";
}
@section header{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Core/assetsCms/tinymce/tinymce.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Core/Scripts/editor/carousel-editor.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Core/assetsCms/css/pageEditor.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Core/assets/css/main.css")" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Areas/Carousel/assets/style.css")" type="text/css" rel="Stylesheet" />
    <script type="text/javascript">
        var sectionId = 1;
    </script>
}
@section cmsButtons{
<p style="text-align: right;">
    @Html.ActionLink("Back to List", "Index", "Item", new { area = "RadCms.Carousel" }, null)
    <a href="#" class="k-button k-primary" id="SaveChange">Save
        @*<img src="@Url.Content("~/Core/assetsCms/images/saveButton.png")" alt="Save" />*@
    </a> 
    <a href="#" class="k-button" id="CancelChange">Cancel
        @*<img src="@Url.Content("~/Core/assetsCms/images/cancelButton.png")" alt="Cancel" />*@
    </a>
</p>
    <div style="display: none">
        @using (Html.BeginForm("Do", "Item", new { id = Model.Id, area = "RadCms.Carousel" }, FormMethod.Post, new { @id = "actForm" }))
        {    
            @Html.HiddenFor(model => model.Id)
            @Html.Hidden("act", "cancel", new { @id = "act" });
        }
    </div>
}
@using (Html.BeginForm("Create", "Item", new { area = "RadCms.Carousel" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <table style="width: 100%; text-align: left;">
        <tr>
            <th>
                @Html.LabelFor(model => model.Title)
            </th>
            <td>
                @Html.TextBoxFor(model => model.Title, new { @class = "k-textbox" })
                @Html.ValidationMessageFor(model => model.Title)
            </td>
        </tr>
        <tr>
            <th>
                @Html.LabelFor(model => model.SlideId)
            </th>
            <td>
                @Html.EditorFor(model => model.SlideId)
                @Html.ValidationMessageFor(model => model.SlideId)
            </td>
        </tr>
        <tr>
            <th>
                @Html.LabelFor(model => model.Visible)
            </th>
            <td>
                @Html.EditorFor(model => model.Visible)
                @Html.ValidationMessageFor(model => model.Visible)
            </td>
        </tr>
    </table>
    <div id="contentOneSource">
        <div class="webpart cms-replaceable" webpartid="carousel" id="carouselWrapper" data-replace="[$webpart(carousel)$]">
            <div class="carouselItem cms-editable" style="left: 0px;">
                <div class="wrapper">
                    <div class="item-container">
                        <div class="item-text-wrapper">
                            <div class="item-title-wrapper">
                                <h2>
                                    How Well Do You Sleep?
                                </h2>
                            </div>
                            <div class="item-desc-wrapper">
                                <p>
                                    Learn your sleep disorder risk using the Anonymous Sleep Disorders Screening Tool.
                                </p>
                            </div>
                        </div>
                        <div class="item-btn-wrapper">
                            <a href="#">Assess Your Risk</a>
                        </div>
                    </div>
                </div>
                <img src="@Url.Content("~/Areas/Carousel/assets/railroader.jpg")" />
            </div>
        </div>
    </div>
    @Html.HiddenFor(model => model.SlideContent)
    <p style="display: none;">
        <input id="submitChange" type="submit" value="Create" />
    </p>
}

RadCms.Web/Areas/Carousel/Views/ItemCms/Delete.cshtml
@model RadCms.Entities.Carousel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Carousel</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">SlideId</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SlideId)
    </div>

    <div class="display-label">Visible</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Visible)
    </div>

    <div class="display-label">SlideContent</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SlideContent)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index", "Item", new { area="RadCms.Carousel"})
    </p>
}

RadCms.Web/Areas/Carousel/Views/ItemCms/Details.cshtml
@model RadCms.Entities.Carousel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Carousel</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">SlideId</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SlideId)
    </div>

    <div class="display-label">Visible</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Visible)
    </div>

    <div class="display-label">SlideContent</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SlideContent)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RadCms.Web/Areas/Carousel/Views/ItemCms/Edit.cshtml
@model RadCms.Entities.Carousel

@{
    ViewBag.Title = "Edit Carousel";
}
@using RadCms.Helpers
@section header{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Core/assetsCms/tinymce/tinymce.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Core/Scripts/editor/carousel-editor.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Core/assetsCms/css/pageEditor.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Core/assets/css/main.css")" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Core/assets/css/content.css")" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Areas/Carousel/assets/style.css")" type="text/css" rel="Stylesheet" />
    <script type="text/javascript">
        var sectionId = 1;
    </script>
    <style type="text/css">
        #tabs
        {
            height: 600px;
        }
        
        .editor-field input
        {
            width: 700px;
        }
        
        .editor-label
        {
            font-weight: bold;
        }
        
        .editor-field
        {
            margin-bottom: 10px;
        }
        
        #bodyWrapper .defaultSkin table.mceLayout
        {
            border: none;
        }
        
        #uploadFile
        {
            width: 415px;
        }
    </style>
}
@section cmsButtons{
<p style="text-align: right;">
    <a href="#" class="k-button k-primary" id="SaveChange">Save
    </a> 
    <a href="#" class="k-button" id="CancelChange">Cancel
    </a>
</p>
    <div style="display: none">
        @using (Html.BeginForm("Do", "ItemCms", new { id = Model.Id }, FormMethod.Post, new { id = "actForm" }))
        {
            @Html.HiddenFor(model => model.Id)
            @Html.Hidden("act", "cancel", new { @id = "act" });
        }
    </div>
}
@using (Html.BeginForm("Edit", "ItemCms", new { id = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*<div id="metadataWrapper">
        @Html.ValidationSummary(true)
        <div class="metaDataField">
            <strong>Title</strong>
            <div>
                @Html.EditorFor(model => model.Title)
                <div>@Html.ValidationMessageFor(model => model.Title)</div>
            </div>
        </div>
        <div id="leftMetaData">
            <div class="metaDataField">
                @Html.EditorFor(model => model.Visible)
                <strong>Visible on home page</strong>
                <div>@Html.ValidationMessageFor(model => model.Visible)</div>
            </div>
        </div>

        <div id="rightMetaData">
            <div class="metaDataField">
                <strong>Slide Id</strong>
                @Html.TextBoxFor(model => model.SlideId)
                <div>@Html.ValidationMessageFor(model => model.SlideId)</div>
            </div>
        </div>
        <div style="clear: both;">
        </div>
    </div>*@
    @Html.ValidationSummary(true)
    <table style="width: 100%; text-align: left;">
        <tr>
            <th>
                @Html.LabelFor(model => model.Title)
            </th>
            <td>
                @Html.TextBoxFor(model => model.Title, new { @class = "k-textbox" })
                @Html.ValidationMessageFor(model => model.Title)
            </td>
        </tr>
        <tr>
            <th>
                @Html.LabelFor(model => model.SlideId)
            </th>
            <td>
                @Html.EditorFor(model => model.SlideId)
                @Html.ValidationMessageFor(model => model.SlideId)
            </td>
        </tr>
        <tr>
            <th>
                @Html.LabelFor(model => model.Visible)
            </th>
            <td>
                @Html.EditorFor(model => model.Visible)
                @Html.ValidationMessageFor(model => model.Visible)
            </td>
        </tr>
    </table>
    <div id="contentOneSource">
        <div class="webpart cms-replaceable" webpartid="carousel" id="carouselWrapper" data-replace="[$webpart(carousel)$]">
            <div class="carouselItem cms-editable" style="left:0px;">
                @Html.Raw(Model.SlideContent)
            </div>
        </div>
    </div>
    @Html.HiddenFor(model => model.Id)
    @*@Html.TextAreaFor(model => model.SlideContent, new { @id = "mainEditor", @class = "mceMainOne" })*@
    @Html.HiddenFor(model => model.SlideContent)
    @Html.ValidationMessageFor(model => model.SlideContent)
    <p style="display: none;">
        <input type="submit" id="submitChange" value="Save" />
    </p>
}

RadCms.Web/Areas/Carousel/Views/ItemCms/Index.cshtml
@model IEnumerable<RadCms.Entities.Carousel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Order
        </th>
        <th>
            Visible
        </th>
        <th>
            Title
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SlideId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Visible)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>