RadCms.Web/Core/Containers/Controllers/PageCmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Text;
using RadCms.Security;

namespace RadCms.Core.Containers.Controllers
{
    using Entities;
    using Models;
    using Helpers;
    using System.Web.Script.Serialization;
    using Mvc;
    using Data;

    public class PageCmsController : CmsControllerBase
    {
        private IPageUrlHelper _urlHelper;
        private IPageEngine _pageEngine;
        private IDbContext _db;

        public PageCmsController(IPageUrlHelper helper, IDbContext db, IPageEngine pageEngine)
        {
            _db = db;
            _pageEngine = pageEngine;
            _urlHelper = helper;
        }

        public ViewResult Manage(int id, int tab = 1)
        {
            var page = _db.Set<CmsPage>().SingleOrDefault(e => e.Id == id);
            if (page != null)
            {
                ViewBag.PageId = id;
                ViewBag.SectionId = page.NaviNode.Id;
            }
            else
            {
                ViewBag.PageId = 1;
                ViewBag.SectionId = 1;
                // TODO hard coded default page for manage page
                page = _db.Set<CmsPage>().Find(1);
            }
            ViewBag.Tab = tab;
            // TODO hard coded page type check
            ViewBag.Page = page;
            ViewBag.SectionType = page.NaviNode.Type.Title;
            ViewBag.IsUser = SecurityHelper.CurrentCmsUser(_db) != null;
            ViewBag.PagePermission = SecurityHelper.PageAccessMode(_db, page);
            return View();
        }

        public ViewResult Index()
        {
            return View(_db.Set<CmsPage>().ToList());
        }

        public ViewResult Details(int id)
        {
            CmsPage page = _db.Set<CmsPage>().Find(id);
            return View(page);
        }

        public ActionResult Version(int id)
        {
            VerPage vPage = _db.Set<VerPage>().SingleOrDefault(e => e.VerId == id);

            if (vPage == null)
            {
                return new HttpNotFoundResult("Page version not found");
            }

            CmsPage page = new CmsPage();

            CopyProperties(vPage, page);

            page.Id = vPage.Id;
            page.NaviNode = _db.Set<NaviNode>().SingleOrDefault(
                e => e.Id == vPage.NaviNodeId);

            StringBuilder webpartHeaders = new StringBuilder();

            bool havingWebPart = false;
            page.ContentHtml.Content = _pageEngine.ReplaceTokens(
                page: page,
                webpartHeaders: webpartHeaders,
                havingWebPart: out havingWebPart,
                controllerContext: this.ControllerContext);

            PermissionType accessMode = SecurityHelper.PageAccessMode(_db, page);
            ViewBag.AccessMode = accessMode;
            ViewBag.VerId = vPage.VerId;
            ViewBag.BaseNode = CmsPageBase.FindBaseNode(page);

            return View(page);
        }

        public ActionResult History(int id)
        {
            ViewData["PageId"] = id;
            return View();
        }
        
        public JsonResult GetHistories(int id)
        {
            var histories =
                (from v in _db.Set<VerPage>()
                 where v.Id == id
                 orderby v.VerId descending
                 select v).Select(e => new { e.IsPublished, e.Title, e.PublishedBy, e.Published, e.VerId }).ToList();

            return Json(new
            {
                histories = histories,
                total = histories.Count
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AnalyzeLinks(int id)
        {
            string friendlyId = CmsPage.ToFriendlyId(id);
            string idPattern = "/" + friendlyId;
            var thisPage = _db.Set<CmsPage>().SingleOrDefault(e => e.Id == id);
            string namePattern = "/" + thisPage.Url;

            List<CmsPage> pages = new List<CmsPage>();

            foreach (var p in _db.Set<CmsPage>().ToList())
            {
                if ((p.ContentHtml.Content != null && p.ContentHtml.Content.IndexOf(idPattern, StringComparison.OrdinalIgnoreCase) > 0)
                    || 
                    (p.ContentHtml.Sidebar != null && p.ContentHtml.Sidebar.IndexOf(idPattern, StringComparison.OrdinalIgnoreCase) > 0) 
                    || 
                    (p.ContentHtml.Content != null && p.ContentHtml.Content.IndexOf(namePattern, StringComparison.OrdinalIgnoreCase) > 0))
                {
                    pages.Add(p);
                }
            }
            ViewBag.ThisPage = thisPage;
            return View(pages);
        }

        public ActionResult Restore(int id)
        {
            VerPage verPage = _db.Set<VerPage>().SingleOrDefault(e => e.VerId == id);

            if (verPage == null)
            {
                throw new Exception("Version is not found.");
            }

            CmsPage cmsPage = _db.Set<CmsPage>().SingleOrDefault(e => e.Id == verPage.Id);

            if (cmsPage != null)
            {
                CopyProperties(verPage, cmsPage);

                PubPage pubpage = _db.Set<PubPage>().SingleOrDefault(e => e.Id == verPage.Id);

                if (pubpage != null && pubpage.Modified == verPage.Modified)
                    cmsPage.Status = CmsPage.STATUS_NORMAL;
                else
                    cmsPage.Status = CmsPage.STATUS_CHANGE_SAVED;

                ((DbContext)_db).Entry(cmsPage).State = EntityState.Modified;
                _db.SaveChanges();
            }

            return Redirect(PageHelper.Goto(verPage.Id, _db));
        }

        [HttpPost]
        public ActionResult Do(string id, string act)
        {
            int internalId = CmsPage.FromFriendlyId(id);
            CmsPage page = _db.Set<CmsPage>().Single(e => e.Id == internalId);

            var accessMode = SecurityHelper.PageAccessMode(_db, page);

            bool isModified = false;

            switch (act)
            {
                #region delete
                case "delete":
                    if (accessMode < PermissionType.Publish)
                    {
                        throw new Exception("Access Denided.");
                    }

                    NaviNode naviNode = page.NaviNode;

                    int parentId = naviNode.Id;

                    int numOfPages = _db.Set<CmsPage>().Where(x => x.NaviNode.Id == parentId).Count();

                    int numOfFolder =
                        _db.Set<NaviNode>().Where(x => x.Parent.Id == parentId).Count();
                    
                    if (numOfPages == 1 && numOfFolder == 0)
                    {
                        //delete both page and folder
                        var pubPages = _db.Set<PubPage>().Where(e=>e.NaviNode.Id == naviNode.Id).ToList();
                        var pages = _db.Set<CmsPage>().Where(e => e.NaviNode.Id == naviNode.Id).ToList();
                        ((DbSet<PubPage>)_db.Set<PubPage>()).RemoveRange(pubPages);
                        ((DbSet<CmsPage>)_db.Set<CmsPage>()).RemoveRange(pages);
                        _db.SaveChanges();
                        
                        NaviNode toBeDeleted = naviNode;
                        var naviParent = naviNode.Parent;
                        _db.Set<NaviNode>().Remove(toBeDeleted);
                        _db.SaveChanges();
                        naviNode = naviParent;
                    }
                    else
                    {
                        PubPage pubPage = _db.Set<PubPage>().SingleOrDefault(p => p.Id == page.Id);
                        if (pubPage != null)
                        {
                            _db.Set<PubPage>().Remove(pubPage);
                        }
                        _db.Set<CmsPage>().Remove(page);
                        _db.SaveChanges();
                    }

                    CmsPage defaultPage = naviNode.Pages.OrderBy(pg => pg.MenuOrder).ThenBy(pg => pg.Id).FirstOrDefault();
                    while (defaultPage == null)
                    {
                        if (naviNode.Id == 1 || naviNode.Parent == null)
                        {
                            throw new Exception("Navigation Error");
                        }

                        naviNode = naviNode.Parent;

                        defaultPage = naviNode.Pages.OrderBy(pg => pg.MenuOrder).ThenBy(pg => pg.Id).FirstOrDefault();
                    }

                    return RedirectToAction("Page", "Cms", new { id = defaultPage.FriendlyId });
                #endregion
                #region unlock
                case "unlock":
                    if (accessMode < PermissionType.Edit)
                    {
                        throw new Exception("Access Denided.");
                    }
                    if (page.Status == CmsPage.STATUS_EDITING_START)
                    {
                        page.Status = CmsPage.STATUS_NORMAL;
                        isModified = true;
                    }
                    else if (page.Status == CmsPage.STATUS_EDITING_AGAIN)
                    {
                        page.Status = CmsPage.STATUS_CHANGE_SAVED;
                        isModified = true;
                    }

                    //db.Entry(page).State = EntityState.Modified;
                    //db.SaveChanges();

                    //return RedirectToAction("Edit", new { id = id });

                    break;
                #endregion
                #region publish
                case "publish":
                    if (accessMode < PermissionType.Publish)
                    {
                        throw new Exception("Access Denided.");
                    }
                    if (page.Status == CmsPage.STATUS_NORMAL
                        || page.Status == CmsPage.STATUS_CHANGE_SAVED)
                    {

RadCms.Web/Core/Containers/Views/PageCms/AnalyzeLinks.cshtml
@using RadCms.Helpers
@using RadCms.Data

@model List<RadCms.Entities.CmsPage>
@{
    ViewBag.Title = "Page Connections";
    Layout = "~/Core/Views/Shared/_LayoutCmsPopup.cshtml";
}
@section header{
    @Styles.Render("~/common/main")
    <style>
        #relationships{
            margin: 20px 0;
        }
        .breadcrumbWrapper{
            line-height: 25px;
        }
        h2
        {
            margin: 0;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function(){
            $('a').click(function (e) {
                e.preventDefault();
            })
        });
    </script>
}
<h2>CURRENT PAGE</h2>
@*@Html.Raw(WebpartHelper.BreadcrumbWebPart(new CmsContext(), ViewBag.ThisPage.Id, ViewBag.ThisPage.NaviNode))*@
<img id="relationships" src="@Url.Content("~/Core/assetsCms/images/relationships.gif")" alt="Relationships" />
@if (Model.Count == 0)
{
<h2>THERE ARE NO PAGES LINKING TO IT</h2>
}
else
{
<h2>PAGES LINKING TO IT</h2>
    foreach (var p in Model)
    { 
        @*@Html.Raw(WebpartHelper.BreadcrumbWebPart(new CmsContext(), p.Id, p.NaviNode))*@
    }
}

RadCms.Web/Core/Containers/Views/PageCms/Create.cshtml
@model RadCms.Core.Containers.Models.EditPageModel
@using RadCms.Helpers
@using RadCms.Entities
@{
    ViewBag.Title = "Create Page";
    Layout = "~/Core/Views/Shared/_LayoutGlobalNew.cshtml";
    bool isSuperUser = RadCms.Security.SecurityHelper.IsSuperUser();
    bool isAdmin = RadCms.Security.SecurityHelper.IsAdmin();
    ViewData["IsAdmin"] = isAdmin;
    ViewData["ViewState"] = "CREATE";
    var actionViewModel = new RadCms.Core.Containers.Models.ActionBarModel
    {
        IsPublished = false,
        Status = RadCms.Entities.CmsPage.STATUS_EDITING_START,
        SectionId = ViewBag.NaviNode.Id,
        ReturnUrl = ViewBag.ReturnUrl,
        ModifiedBy = HttpContext.Current.User.Identity.Name,
        LastModified = DateTime.Now,
        AccessMode = ViewBag.AccessMode ?? PermissionType.Denied,
    };
}
@section header{
    <link href="@Url.Content("~/layout/styles/" + Model.Layout)" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Core/assetsCms/css/pageEditor.css")" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Core/assetsCms/tinymce/tinymce.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Core/Scripts/editor/cms-editor.js")" type="text/javascript"></script>
    <script type="text/javascript">
        var sectionId = "@(ViewBag.NaviNode.Id)";
        $(document).ready(function () {
            if ($('#isCreateNewSection').is(":checked")) {
                $('#newSectionMetaData').show();
            }

            $('#isCreateNewSection').change(function () {
                if (this.checked) {
                    $('#newSectionMetaData').show();
                }
                else {
                    $('#newSectionMetaData').hide();
                }
            });

        });
    </script>
    <style type="text/css">
        @Html.BackgroundStyle(Model.Status)
        .header-container{
            background-position: 0 268px;
        }
        #headerTop{
            margin-top: 268px;
        }
        #newSectionMetaData{
            display: none;
        }
        .field-validation-error{
            display: inline;
        }
    </style>
    @if (!isAdmin)
    {  
        <style type="text/css">
            #rightMetaData, #leftMetaData{
                width: 49%;
            }
        </style>
    }

    @Html.Raw(ViewBag.WebpartHeaders)
}
@section leftActionBar{
    @Html.Partial("_LeftEditBarPartial", actionViewModel)
}
@section rightActionBar{
}
@section statusBar{
    @Html.Partial("_MessageBarPartial", actionViewModel)
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.Partial("_EditFormPartial", Model, ViewData)
    <p style="display: none">
        <input type="submit" id="submitChange" value="Save" />
    </p>
}

RadCms.Web/Core/Containers/Views/PageCms/Details.cshtml
@model RadCms.Entities.CmsPage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Page</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">Keywords</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Keywords)
    </div>



    <div class="display-label">IsPublished</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsPublished)
    </div>

    <div class="display-label">CreatedBy</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedBy)
    </div>

    <div class="display-label">Created</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">ModifiedBy</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModifiedBy)
    </div>

    <div class="display-label">Modified</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modified)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RadCms.Web/Core/Containers/Views/PageCms/Edit.cshtml
@model RadCms.Core.Containers.Models.EditPageModel
@using RadCms.Helpers
@{
    ViewBag.Title = "Edit Page";
    Layout = "~/Core/Views/Shared/_LayoutGlobalNew.cshtml";
    bool isSuperUser = RadCms.Security.SecurityHelper.IsSuperUser();
    bool isAdmin = RadCms.Security.SecurityHelper.IsAdmin();
    ViewData["IsAdmin"] = isAdmin;
    ViewData["ViewState"] = "EDIT";
    var actionViewModel = new RadCms.Core.Containers.Models.ActionBarModel
    {
        Id = Model.Id,
        IsPublished = Model.IsPublished,
        Status = ViewBag.Status,
        SectionId = ViewBag.NaviNode.Id,
        ModifiedBy = ViewBag.ModifiedBy,
        LastModified = ViewBag.Modified,
        AccessMode = ViewBag.AccessMode,
    };

}

@section header{
    <link href="@Url.Content("~/layout/styles/" + Model.Layout)" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Core/assetsCms/css/pageEditor.css")" rel="stylesheet" type="text/css" />
    <style>
        @Html.BackgroundStyle(Model.Status)
        .header-container{
            background-position: 0 224px;
        }
        #headerTop{
            margin-top: 224px;
        }
        .field-validation-error{
            display: inline;
        }
    </style>
    @if (!isAdmin)
    {  
        <style type="text/css">
            #rightMetaData, #leftMetaData{
                width: 49%;
            }
        </style>
    }
    
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Core/assetsCms/tinymce/tinymce.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Core/Scripts/editor/cms-editor.js")" type="text/javascript"></script>
    <script type="text/javascript">
        var sectionId = "@(ViewBag.NaviNode.Id)";
        var pageLayoutId = "@(Model.Layout)";
        var baseUrl = "@Url.Content("~/")";
    </script>
    @Html.Raw(ViewBag.WebpartHeaders)
}
@section leftActionBar{
    @Html.Partial("~/Core/Containers/Views/PageCms/_LeftEditBarPartial.cshtml", actionViewModel)
}
@section rightActionBar{
}

@section statusBar{
    @Html.Partial("~/Core/Containers/Views/PageCms/_MessageBarPartial.cshtml", actionViewModel)
}
@using (Html.BeginForm(new { id = Model.Id }))
{
    @Html.ValidationSummary(true)
    @Html.Partial("~/Core/Containers/Views/PageCms/_EditFormPartial.cshtml", Model, ViewData)
    <p style="display: none">
        <input type="submit" id="submitChange" value="Save" />
    </p>
}

RadCms.Web/Core/Containers/Views/PageCms/History.cshtml
@{
    ViewBag.Title = "Page History";
    Layout = "~/Core/Views/Shared/_LayoutCmsPopup.cshtml";      
}

@section header{
    <style type="text/css">
        a.newitem
        {
            background-image: url('~/Core/assetsCms/images/newitem.gif');
            background-repeat: no-repeat;
            padding-left: 20px;
        }
        
        .sectionToolbar a.reorder
        {
            background-image: url('~/Core/assetsCms/images/reorder.gif');
            background-repeat: no-repeat;
            padding-left: 20px;
        }
        
        #historyTable
        {
            width: 100%;
        }
    </style>
    <script type="text/javascript">
        var pageId = @ViewData["PageId"];
    </script>
<link rel="stylesheet" type="text/css" href="~/Core/Content/datatables/datatables.min.css" />

<script type="text/javascript" src="~/Core/Content/datatables/datatables.min.js"></script>
<script type="text/javascript" src="~/Core/Content/moment/moment.min.js"></script>
    @Scripts.Render("~/Core/scripts/cms/cms-manage-history.js")
}

<table id="historyGrid" >
    <thead>
        <tr>
            <th>Title</th>
            <th>Date Published</th>
            <th>Published By</th>
            <th></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Title</th>
            <th>Date Published</th>
            <th>Published By</th>
            <th></th>
        </tr>
    </tfoot>
</table>
<div id="noHistory" style="display: none;">
    <p>
        Current page does not have any history version.
    </p>
</div>

RadCms.Web/Core/Containers/Views/PageCms/Version.cshtml
@model RadCms.Entities.IPage
@{
    ViewBag.Title = "Web Page - " + Model.Title;
    Layout = "~/Core/Views/Shared/_LayoutGlobalNew.cshtml";
    var accessMode = ViewBag.AccessMode;
    var actionViewModel = new RadCms.Core.Containers.Models.ActionBarModel
    {
        Id = Model.Id,
        IsPublished = Model.IsPublished,
        Status = Model.Status,
        SectionId = Model.NaviNode.Id,
        ModifiedBy = Model.ModifiedBy,
        LastModified = Model.Modified,
        AccessMode = accessMode,
    };
}
@using RadCms.Helpers
@using RadCms.Entities
@section header{
    <link href="@Url.Content("~/layout/styles/" + Model.Layout)" type="text/css" rel="Stylesheet" />
    <style type="text/css">
        @Html.BackgroundStyle(Model.Status)
        .header-container{
            background-position: 0 100px;
        }
        #headerTop{
            margin-top: 100px;
        }
    </style>
    
    <script src="/Core/Scripts/cms/cms-comm.js" type="text/javascript"></script>
    <script src="/Core/Scripts/cms/cmsPage.js" type="text/javascript"></script>
    <script type="text/javascript">
        var currentPageId = "@(Model.Id)";
        var pageLayoutId = "@(Model.Layout)";

        function restore() {
            $('#actForm').submit();
        }

    </script>
    @Html.Raw(Model.ContentHtml == null ? "" : Model.ContentHtml.Header)
    @Html.Raw(ViewBag.WebpartHeaders)
}
@section leftActionBar{
    @{Html.RenderPartial("~/Core/Containers/Views/PageCms/_LeftVersionBarPartial.cshtml", actionViewModel);}
    @if (ViewBag.AccessMode >= PermissionType.Edit)
{
    <div style="display: none">
        @using (Html.BeginForm("Restore", "PageCms", new { id = ViewBag.VerId, area = "Containers" }, FormMethod.Post, new { @id = "actForm" }))
        {
        }
    </div>
}
}
@section rightActionBar {
    @Html.Partial("~/Core/Containers/Views/PageCms/_RightVersionBarPartial.cshtml", actionViewModel)
}
@section statusBar{
    @Html.Partial("~/Core/Containers/Views/PageCms/_MessageBarPartial.cshtml", actionViewModel)
}
<div id="contentWrapper" class="clear-fix">
    @Html.Raw(Model.ContentHtml.Content)
</div>

RadCms.Web/Core/Containers/Views/PageCms/_LeftActionBarPartial.cshtml
@using RadCms.Entities
@using RadCms.Helpers
@model RadCms.Core.Containers.Models.ActionBarModel
<div id="leftToolBar"></div>
@{
    var showPublish = false;
    var showEditDraft = false;
    var showEditPage = false;
    var showRequestAccess = false;
    var showUnlock = false;
    var showEditWebParts = false;
    var pageLabel = Model.Type.Title == "BLOG" ? "POST" : "PAGE";

    switch (Model.Status)
    {
        case CmsPageBase.STATUS_CHANGE_SAVED:
            if(Model.AccessMode >= PermissionType.Publish){
                showEditWebParts = true;
                showPublish = true;
            }
            if (Model.AccessMode >= PermissionType.Edit)
            {
                showEditDraft = true;
            }
            break;
        case CmsPageBase.STATUS_EDITING_BY_OTHERS:
            if (Model.AccessMode >= PermissionType.Publish)
            {
                showEditWebParts = true;
            }
            goto case CmsPageBase.STATUS_EDITING_AGAIN;
        case CmsPageBase.STATUS_EDITING_START:
        case CmsPageBase.STATUS_EDITING_AGAIN:
            string userName = null;
            if (HttpContext.Current != null && HttpContext.Current.User != null)
            {
                userName = HttpContext.Current.User.Identity.Name.ToUpper();
            }
            if (userName != null && userName == Model.ModifiedBy && Model.AccessMode >= PermissionType.Edit)
            {
                showEditDraft = true;
            }
            else
            {
                if (Model.AccessMode >= PermissionType.Edit)
                {
                    showUnlock = true;
                }
            }
            break;
        case CmsPageBase.STATUS_NORMAL:
        default:
            if (Model.AccessMode >= PermissionType.Publish)
            {
                showEditWebParts = true;
            }
            if (Model.AccessMode >= PermissionType.Edit)
            {
                showEditPage = true;
            }
            break;
    }

    if (Model.Id != 1)
    {
        if(CmsHelper.Site == "fratalk")
        {
            showEditWebParts= Model.Type.Title =="BLOG";
        }
    }

    if (Model.AccessMode <= PermissionType.Default)
    {
        showRequestAccess = true;
    }

    if (Model.AccessMode >= PermissionType.Edit)
    {
<div style="display: none">
    @using (Html.BeginForm("Do", "PageCms", new { id = Model.FriendlyId, area = "Containers" }, FormMethod.Post, new { @id = "actForm" }))
    {
            @Html.Hidden("act", null, new { @id = "act" });
        }
</div>
    }
}

<script type="text/javascript">
    $(document).ready(function () {
        var site = "@(CmsHelper.Site)";
        var True = true;
        var False = false;
        var barConfig = {
            pageLabel: "@(pageLabel)",
            showPublish: @(showPublish),
            showEditDraft: @(showEditDraft),
            showEditPage: @(showEditPage),
            showRequestAccess: @(showRequestAccess),
            showUnlock: @(showUnlock),
            showEditWebParts: @(showEditWebParts),
        };

        var items = [];

        if(barConfig.showPublish){
            items.push({
                type: "button",
                text: "PUBLISH THIS " + barConfig.pageLabel,
                spriteCssClass: "cms-icon cms-icon-publish",
                overflow: 'never',
                attributes: {"id":"publishBtn"},
                click: CMS.PAGE.publish});
        }

        if(barConfig.showEditDraft){
            items.push({
                type: "button",
                text: "EDIT THIS DRAFT",
                spriteCssClass: "cms-icon cms-icon-editdraft",
                overflow: 'never',
                attributes: {"id":"editDraftBtn"},
                click: CMS.PAGE.edit});
        }

        if(barConfig.showEditPage){
            items.push({
                type: "button",
                text: "EDIT THIS " + barConfig.pageLabel,
                spriteCssClass: "cms-icon cms-icon-edit",
                overflow: "never",
                attributes: {"id": "editPageBtn"},
                click: CMS.PAGE.edit
            });
        }
        
        if(barConfig.showEditWebParts){
            items.push({
                type: 'button',
                text: site === 'fratalk'? 'MANAGE COMMENTS': 'EDIT WEBPARTS',
                spriteCssClass: 'cms-icon cms-icon-webpart',
                overflow: 'never',
                'attributes': {id: 'editWebPartsBtn'},
                click: CMS.PAGE.editWebParts
            });
        }

        if(barConfig.showUnlock){
            items.push({
                type: "button",
                text: "EDIT THIS " + barConfig.pageLabel,
                spriteCssClass: "cms-icon cms-icon-edit",
                overflow: "never",
                attributes: {"id": "editPageBtn"},
                click: CMS.PAGE.unlock
            });
        }
        $('#leftToolBar').kendoToolBar({
            resizable: false,
            items: items
        });
    });
</script>

RadCms.Web/Core/Containers/Views/PageCms/_LeftEditBarPartial.cshtml
@model RadCms.Core.Containers.Models.ActionBarModel
@{
    bool isNewPage = false;
    // Only put return url when it's create page mode.
    if (!string.IsNullOrEmpty(Model.ReturnUrl))
    {
        isNewPage = true;
    }
}
<div id="leftToolBar">
</div>
<div style="display: none">
    @using (Html.BeginForm("Do", "PageCms", new { id = Model.Id }, FormMethod.Post, new { @id = "actForm" }))
    {    
        @Html.HiddenFor(model => model.Id)
        @Html.Hidden("act", "cancel", new { @id = "act" });
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var items = [];
        var False = false;
        var True = true;
        var isNewPage = @(isNewPage);
        
        items.push({
            type: "button",
            text: "SAVE MY CHANGES",
            spriteCssClass: "cms-icon cms-icon-save",
            overflow: 'never',
            attributes: { "id": "saveBtn" },
            click: saveChange
        });
        if(isNewPage){
            items.push({
                type: "button",
                text: "CANCEL",
                spriteCssClass: "cms-icon cms-icon-cancel",
                overflow: 'never',
                attributes: { "id": "cancelBtn" },
                click: function(){
                    window.location.href = "@(Model.ReturnUrl)";
                }
            });
        }
        else{
            items.push({
                type: "button",
                text: "CANCEL",
                spriteCssClass: "cms-icon cms-icon-cancel",
                overflow: 'never',
                attributes: { "id": "cancelBtn" },
                click: cancelChange
            });
        }

        $('#leftToolBar').kendoToolBar({
            resizable: false,
            items: items
        });
    });
</script>